### ISSUE TITLE
allow for viewing a public profile

### ISSUE THREAD

**Issue by satra** [linkeddata/profile-editor#17]
it would be good to be able to make components of the profile public that can be viewed by anyone without authorization. more fundamentally i think this should be enabled somehow in solid.

![image](https://cloud.githubusercontent.com/assets/184063/13959222/bd3bb1b8-f029-11e5-8472-12eae5b520b6.png)

**Comment by satra** [comment]
more generally this would be about permitting anonymous access as an option.

**Comment by satra** [comment]
never mind the solid comment. this works in solid: `curl -D - -L -H "Accept: text/turtle" https://satra.databox.me/profile/card#me`

but it would be nice if the profile app showed a view only version of the public components of the profile without someone authenticating.

**Comment by dmitrizagidulin** [comment]
Hi @satra, thanks for opening the issue. 
Quick question - by 'view only version', do you mean like a human-readable HTML rendering of the profile? 
If yes, I agree, it is something we need to add. 

The WebID profile is actually supposed to be explicitly public. (The reason it still prompts you for authentication in the browser is legacy behavior that we'll be fixing soon. You can actually press Cancel during that popup and not authenticate.)
The profile can link to other, private documents, but it itself is supposed to be public.

**Comment by satra** [comment]
i'm going to close this. i figured out how to do this properly. in my solid generator, i did the following and now it works.

`href="profile/#/profile/view?webid=https:%2F%2Fsatra.databox.me%2Fprofile%2Fcard%23me"`
