### ISSUE TITLE
Broken Viewer link: ":" missing between "http" and "//" 

### ISSUE THREAD

**Issue by akuckartz** [linkeddata/profile-editor#7]
http://linkeddata.github.io/profile-editor/#/share contains a link "Viewer link":

```
http//linkeddata.github.io/profile-editor//#/profile/view?webid=https%3A%2F%2Fakuckartz.databox.me%2Fprofile%2Fcard%23me
```

There is no ":" between "http" and "//"

**Comment by deiu** [comment]
Fixed in cb0a97a7ad26880a21cf1b472ee7a6642d8cf1cf
